version: '3.6'
services:
  web:
    hostname: 'gitlab.raul.com'
    container_name: gitlab-ee-latest
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.raul.com'
        # Add any other gitlab.rb configuration here, each on its own linex
    ports:
      - '8080:80'
      - '3443:443'
      - '222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '2gb'