version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5445:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      - PASSWORD=docker
    restart: always