version: '2.2'
services:
    dynamo:
        image: amazon/dynamodb-local
        container_name: registry_config
        ports:
            - 8000:8000
        networks:
            - lambda-local

networks:
     lambda-local:
        driver: bridge
