version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    user: root
    ports:
      - 8008:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/jenkins:/var/jenkins_home
    environment:
      - JENKINS_PASSWORD=docker
    restart: always